source 'https://rubygems.org'
ruby '2.1.3'

gem 'cocoapods'
gem 'cocoapods-core', git:"https://github.com/CocoaPods/Core.git"
gem 'flounder', require: true
gem 'redcarpet'
gem 'data_objects'

gem 'awesome_print'
